# Generated by Django 3.2.15 on 2023-01-06 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('tutor', '0003_auto_20230104_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='errores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='primerintento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EstudianteTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tema')),
            ],
        ),
    ]
