# Generated by Django 3.2.15 on 2023-01-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20230106_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='primerintento',
            field=models.BooleanField(default=False),
        ),
    ]
