# Generated by Django 3.2.15 on 2023-01-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_alter_ejercicio_primerintento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantetema',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materia',
            name='corto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
