# Generated by Django 3.2.15 on 2023-02-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20230111_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
