# Generated by Django 3.2.15 on 2023-02-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_tema_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='errores',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='intentos',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='primerintento',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='resuelto',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='opciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
