# Generated by Django 3.2.15 on 2023-02-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_auto_20230210_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='fecha',
        ),
    ]
