# Generated by Django 3.2.15 on 2023-03-07 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('tutor', '0010_ejercicio_dificultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcto', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(auto_now=True)),
                ('intentos', models.IntegerField(default=0)),
                ('primera_respuesta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.ejercicio')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
    ]
