# Generated by Django 3.2.15 on 2023-03-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_estudianteejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantetema',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
    ]
