# Generated by Django 3.2.15 on 2023-03-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_alter_estudiantetema_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteejercicio',
            name='primera_respuesta',
            field=models.BooleanField(default=False),
        ),
    ]
