# Generated by Django 3.2.15 on 2023-03-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_alter_estudianteejercicio_primera_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteejercicio',
            name='correctos',
            field=models.IntegerField(default=0, verbose_name='VecesCorrecto'),
        ),
    ]
