# Generated by Django 3.2.15 on 2023-04-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0017_auto_20230318_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='explicacion',
            name='voz_texto',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
