# Generated by Django 3.2.15 on 2023-04-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0018_explicacion_voz_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='explicacion',
            name='dificultad',
            field=models.IntegerField(default=1),
        ),
    ]
