# Generated by Django 3.2.15 on 2023-04-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0019_explicacion_dificultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='explicacion',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
