# Generated by Django 3.2.15 on 2023-05-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nivel_acceso',
            field=models.IntegerField(default=1),
        ),
    ]
